# docker compose version
version: '3.8'

# services => containers
services:    
  edusys_db:
    container_name: edusys_db
    image: postgres:12
    ports:
      - 5432:5432  # laptop_port:container_port
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_DB=edudb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'DATABASE_HOST=edusys_db'
      - 'DATABASE_PORT=5432'
  
  edusys_api:
    container_name: edusys_api
    build: 
      context: ./drf # content of the local directory [docker-compose folder]
      dockerfile: Dockerfile
    # command: gunicorn config.wsgi -b 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./drf:/usr/src/drf # wd/path/on/laptop:wd/path/in/container
      - web_static:/usr/src/drf/static
    ports:
      - 8000:8000  # laptop_port:container_port
      - 3000:3000  # debugger port
    depends_on:
      - edusys_db

  edusys_app:
    container_name: edusys_app
    build:
      context: ./vue
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./vue:/usr/src/vue
    ports:
      - 8080:8080

volumes:
  postgres_data:
  web_static: